language : node_js
node_js:
 - node
os:
 - linux
 - osx
install:
 - npm install
before_script:
 - npm run transpile
script:
 - npm run lint
 - npm run test
 - npm run nyc
after_script: 
 - npm run cover