node_js:
  - nodejs_version: "12"
  - nodejs_version: "14"

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm run lint
  - npm test

# Don't actually build.
build: off 
