# Uses ubuntu
image: Ubuntu

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "12"

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run lint
  - npm test

# Don't actually build.
build: off